# Generated by Django 4.0 on 2021-12-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('url', models.URLField(help_text='Long url', max_length=2000)),
                ('slug', models.SlugField(help_text='Easy to remember short url', max_length=100, primary_key=True, serialize=False)),
                ('hits', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
